# Dockerfile for launching dch tool
#
# Usage for latest version (Debian w/nginx repo or Ubuntu) (always use stretch as it is replaced before build) :
#   docker build -t deb-dch -f Dockerfile-deb-dch .
#   docker run -it -v $PWD:/local -e HOME=/local deb-dch bash -c 'cd /local && \
#       dch -M -v 1.13.35.2+nginx-1.14.2-1~stretch --distribution "stretch" "Updated upstream."'
#
# Usage for stretch-backports version (Usually not the latest) (always use stretch as it is replaced before build) :
#   docker build -t deb-dch -f Dockerfile-deb-dch .
#   docker run -it -v $PWD:/local -e HOME=/local deb-dch bash -c 'cd /local && \
#       dch -M -v 1.13.35.2+nginx-1.14.1-1~stretch --distribution "stretch" "Updated upstream."'
#

ARG DISTRIB=debian
ARG RELEASE=stretch

FROM debian:stretch-backports
MAINTAINER Cyril Aknine "caknine@clever-age.com"

ENV TZ=Europe/Paris

RUN apt-get update && apt-get --no-install-recommends --no-install-suggests -y install devscripts libdistro-info-perl
